#ifndef PICTURESMODELVIEW_GLOBAL_H
#define PICTURESMODELVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THUMBNAILMANAGER_LIBRARY)
#  define THUMBNAILMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define THUMBNAILMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PICTURESMODELVIEW_GLOBAL_H
